Vagrant.configure("2") do |config|

  config.vm.define "centos" do |c|
	c.vm.provider "virtualbox" do |v|
	  v.name = "centos"
	  v.memory = 1024
	  v.cpus = 2
	  v.gui = false
	end
	c.vm.box = "centos/8"
	c.vm.hostname = "centos"
	c.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "ubuntu" do |c|
	c.vm.provider "virtualbox" do |v|
	  v.name = "ubuntu"
	  v.memory = 1024
	  v.cpus = 2
	  v.gui = false
	end
	c.vm.box = "ubuntu/bionic64"
	c.vm.hostname = "ubuntu"
	c.vm.network "private_network", ip: "192.168.33.11"
  end

end
